site_name: Hyperbolic Optics
site_url: https://hyperbolic-optics.github.io/hyperbolic-optics/
site_description: 4×4 Transfer Matrix Method for Anisotropic Multilayer Structures
site_author: Mark Cunningham
repo_url: https://github.com/hyperbolic-optics/hyperbolic-optics
repo_name: hyperbolic-optics/hyperbolic-optics

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            # Performance optimizations
            members_order: source  # Faster than alphabetical
            show_signature_annotations: false  # Skip if not needed
            separate_signature: true
            merge_init_into_class: true
      # Enable caching
      enable_inventory: true
      # custom_templates: templates  # Only if you have custom templates

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['.']  # This allows it to find your examples/ folder
      check_paths: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Basic Concepts: user-guide/concepts.md
    - Scenarios: user-guide/scenarios.md
    - Materials: user-guide/materials.md
    - Mueller Matrices: user-guide/mueller.md
  - Examples:
    - Basic Examples: examples/basic.md
  - API Reference:
    - api/structure.md
    - api/materials.md
    - api/layers.md
    - api/mueller.md
    - api/scenario.md
    - api/plots.md
  - Contributing: contributing.md
  - Citation: citation.md